spring.application.name=backend


spring.datasource.url=jdbc:postgresql://localhost:5431/tehredact
spring.datasource.username=root
spring.datasource.password=qwertyuiop

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect